### ISSUE TITLE
svg-sprite does not work with absolute paths

### ISSUE THREAD

**Issue by KnisterPeter** [kiliman/rmx-cli#14]
We would like to integrate `rmx svg-sprite` in our pre-processing pipeline to generate icons for us.
But it does not work with absolute input/output paths since in `normalizeFolder` the leading slash is always removed.

Is it possible to change that behavior? I would create a PR if it's welcome.

**Comment by kiliman** [comment]
A PR would be great. The assumption was that the path would be relative to the project root. Thanks!

**Comment by KnisterPeter** [comment]
Cool. Then I will keep the existing behavior if (and only if) the resolved path starts with the cwd.
That should be fine and still support absolute paths.
