### ISSUE TITLE
[Feature Request]: Make the template a javascript file

### ISSUE THREAD

**Issue by KnisterPeter** [kiliman/rmx-cli#16]
Can we extend the template parameter to accept javascript files?
That would enable to execute e.g. the default export from that file with the current icon name/file/... and make the template more dynamic.

Reason: We have several icon sets we need to use and would like to put all of them in a single created icon list. The svg we need to create is slighly different per icon set.

(Here as well I would love to create PR for that)

**Comment by kiliman** [comment]
What is the generator's responsibility, and what does the script do? 

What generates the sprite file? The icon component?

The way it currently works is that it generates a sprite/component per folder. So if you have multiple icon sets like `heroicons`, you can add each set separately. See the example on the home page.

**Comment by KnisterPeter** [comment]
After thinking a bit more about this I'm unsure what exactly will help me here.
I will have to play around with options and will close this for now. When I have a better reasoning I might reopen this again if you don't mind.
