### ISSUE TITLE
svg-sprite's --sprite option is ignored

### ISSUE THREAD

**Issue by wKovacs64** [kiliman/rmx-cli#19]
Looks like it's parsed and [stored in the `sprite` variable](https://github.com/kiliman/rmx-cli/blob/79913e07e3b5d4aa6e9aca9b2f1c3cc881b95753/src/commands/svg-sprite.ts#L33), but that variable is unused and the sprite output [uses the `component` name instead](https://github.com/kiliman/rmx-cli/blob/79913e07e3b5d4aa6e9aca9b2f1c3cc881b95753/src/commands/svg-sprite.ts#L127).

**Comment by kiliman** [comment]
Fixed in v0.4.14
