### ISSUE TITLE
Keep fill options unchanged

### ISSUE THREAD

**Issue by philpieper** [kiliman/rmx-cli#24]
**Problem**
I have svg files with different fill options that shouldn't be replaced with `currentColor` because they are multicolor or dualtone icons.
<img width="1431" alt="Screenshot 2024-04-19 at 14 55 41" src="https://github.com/kiliman/rmx-cli/assets/120683119/72ce3894-d6c0-42ba-9358-d6a463f614ec">

after generating the svg-sprite, my icons look like this:
<img width="1014" alt="Screenshot 2024-04-19 at 14 57 29" src="https://github.com/kiliman/rmx-cli/assets/120683119/50f80621-113e-41df-b371-7b05bafe08b4">

Is there a way to disable the replacement of the fill options with `currentColor`?

**Comment by philpieper** [comment]
I will think about a solution and provide a PR but every input is welcomed

**Comment by kiliman** [comment]
Good morning. Yes, the tool currently replaces the fill with `currentColor`. This is mainly so you can use them as icons and set the color using CSS.

I can add a `--fill=keep` (with default `--fill=currentColor`).

>NOTE: this setting will apply to all SVG files processed. So if you do want `currentColor`, you'll either need to ensure your SVG already contain this value, or you'll need to run the CLI separately for each fill mode.

```
--fill=COLOR     : specify fill color or "keep" to keep original colors
                   default is "currentColor"
--stroke=COLOR   : specify stroke color or "keep" to keep original colors
                   default is "currentColor"
```

**Comment by kiliman** [comment]
Added in v0.4.16 d1de1f34fbf0a41228a1a0a34a3c7fb32034aaa2

**Comment by philpieper** [comment]
Hey, thank you very much. I will try that out :)

**Comment by philpieper** [comment]
> Added in v0.4.16 [d1de1f3](https://github.com/kiliman/rmx-cli/commit/d1de1f34fbf0a41228a1a0a34a3c7fb32034aaa2)

@kiliman Hey! Works good for me but now when I have a `<rect>` defined, rmx will remove width and height causing problems for my svgs.

I mean, I could turn my `rect` into `paths`. But are you aware of this?

**Comment by kiliman** [comment]
Because it strips out width and height from the SVGs. This tool was meant to support icons, not all SVGs. This way, you can use CSS to control color and size.

It seems like you should just do `<img src={svgPath}>` if you're trying to use a custom SVG.

**Comment by philpieper** [comment]
All right, thanks. Yeah we need those svg sprites but also have some more complex icons. There is a workaround though <rect> -> <path>
