### ISSUE TITLE
Live reload doesn't work anymore

### ISSUE THREAD

**Issue by kwiat1990** [kiliman/rmx-cli#7]
Hey, I don't quite know if there's a problem with your plugin or with express adapter in general but after I extracted `server.js` with your plugin, the live reload functionality doesn't work anymore. I need to re-run `npm run dev` command manually in order to see any kind of changes.

My scripts:
```json
    "build": "run-s build:*",
    "build:css": "npm run generate:css -- --minify",
    "build:remix": "remix build",
    "dev": "NODE_ENV=development run-p \"dev:*\"",
    "dev:css": "npm run generate:css -- --watch",
    "dev:remix": "remix watch",
    "generate:css": "npx tailwindcss -i ./app/styles/tailwind.css -o ./app/tailwind.css",
    "start": "node ./server.js",
    "dev:node": "nodemon ./server.js --watch ./server.js"
```

Is there any workaround?

**Comment by kiliman** [comment]
You may need to update your *remix.config* and add `devServerPort: 8002`. Although the docs say there's a default value, I don't think it works properly with Express unless you specify it explicitly. This was an update to later versions of `<LiveReload/>` that used dynamic ports. Let me know if you're still having issues.

https://remix.run/docs/en/v1/api/conventions#devserverport

**Comment by kwiat1990** [comment]
With the port specified in config file all the changes are visible after manual page reload in browser, so it's still not the same automatic reload one becomes with the default Remix server setup, but I think it's good enough if I can have full control over a server cache.

**Comment by kiliman** [comment]
Closing this issue. You can re-open if you still have the problem.
